"""
Output module for Ahgen Media Manager.

Saves briefings as timestamped markdown files and formats HTML email digests.
No browser automation — LinkedIn posting is human-reviewed from markdown drafts.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Optional

log = logging.getLogger("ahgen.poster")

BASE_DIR = Path(__file__).parent
DRAFTS_DIR = BASE_DIR / "drafts"


def save_briefing_to_disk(
    briefing: str,
    drafts: List[Dict],
    output_dir: Optional[Path] = None,
) -> Path:
    """Save morning briefing + post drafts as a timestamped markdown file.

    Returns the path to the saved file.
    """
    out_dir = output_dir or DRAFTS_DIR
    out_dir.mkdir(exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    filepath = out_dir / f"briefing-{ts}.md"

    lines = [f"# Ahgen Morning Briefing — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"]

    if briefing:
        lines.append(briefing)
        lines.append("")

    if drafts:
        lines.append("---\n")
        lines.append("## Post Drafts\n")
        for i, draft in enumerate(drafts, 1):
            summary = draft.get("summary", f"Draft {i}")
            urgency = draft.get("urgency", "medium").upper()
            source = draft.get("source", "unknown")
            lines.append(f"### {i}. [{urgency}] {summary}\n")
            lines.append(f"**Source:** {source}\n")

            globe = draft.get("global_post") or draft.get("global_draft") or {}
            china = draft.get("china_post") or draft.get("china_draft") or {}

            if globe.get("text"):
                lines.append(f"**LinkedIn (EN):**\n{globe['text']}\n")
            if china.get("text"):
                lines.append(f"**WeChat (ZH):**\n{china['text']}\n")

    filepath.write_text("\n".join(lines), encoding="utf-8")
    log.info(f"Briefing saved: {filepath}")
    return filepath


def format_briefing_email(briefing: str, drafts: List[Dict]) -> str:
    """Format briefing + drafts as an HTML email body."""
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html_parts = [
        "<html><body style='font-family: -apple-system, Arial, sans-serif; max-width: 680px; margin: 0 auto;'>",
        f"<h1 style='border-bottom: 2px solid #333; padding-bottom: 8px;'>Ahgen Morning Briefing</h1>",
        f"<p style='color: #666; font-size: 13px;'>{date_str}</p>",
    ]

    if briefing:
        # Convert markdown-ish briefing to simple HTML paragraphs
        for para in briefing.split("\n\n"):
            para = para.strip()
            if not para:
                continue
            if para.startswith("# "):
                html_parts.append(f"<h2>{para[2:]}</h2>")
            elif para.startswith("## "):
                html_parts.append(f"<h3>{para[3:]}</h3>")
            elif para.startswith("- "):
                items = [f"<li>{line.lstrip('- ')}</li>" for line in para.split("\n") if line.strip()]
                html_parts.append(f"<ul>{''.join(items)}</ul>")
            else:
                html_parts.append(f"<p>{para}</p>")

    if drafts:
        html_parts.append("<hr style='margin: 24px 0;'>")
        html_parts.append("<h2>Post Drafts (Ready for LinkedIn)</h2>")

        for i, draft in enumerate(drafts, 1):
            summary = draft.get("summary", f"Draft {i}")
            urgency = draft.get("urgency", "medium").upper()
            source = draft.get("source", "unknown")

            color = {"HIGH": "#c0392b", "MEDIUM": "#e67e22", "LOW": "#27ae60"}.get(urgency, "#666")

            html_parts.append(
                f"<div style='margin: 16px 0; padding: 12px; border-left: 4px solid {color}; background: #f9f9f9;'>"
            )
            html_parts.append(
                f"<strong style='color: {color};'>[{urgency}]</strong> {summary} "
                f"<span style='color: #999; font-size: 12px;'>via {source}</span>"
            )

            globe = draft.get("global_post") or draft.get("global_draft") or {}
            if globe.get("text"):
                html_parts.append(f"<p style='margin: 8px 0 0 0; white-space: pre-wrap;'>{globe['text']}</p>")

            html_parts.append("</div>")

    html_parts.append(
        "<p style='color: #999; font-size: 11px; margin-top: 32px; border-top: 1px solid #eee; padding-top: 8px;'>"
        "Generated by Ahgen Media Manager for ERP Access, Inc.</p>"
    )
    html_parts.append("</body></html>")

    return "\n".join(html_parts)
